### ISSUE TITLE
Register a post type as a FacetWP queryable

### ISSUE THREAD

**Issue by excelify** [hsimah-services/wp-graphql-facetwp#20]
I am trying to use your wp-graphql-facetwp plugin and register the "register_graphql_facet_type()". I followed the doc's but get Uncaught Error.

WordPress v5.6
FacetWP v3.7
WPGraphQL v1.0.5

I added the function call in the theme functions.php file. I also have a facet setup.

// Register facet for Posts 
register_graphql_facet_type( 'post' );

Uncaught Error: Call to undefined function register_graphql_facet_type()
Stack trace:
#0 wp-settings.php(525): include()
#1 wp-config.php(99): require_once('/home/ionicexce...')
#2 wp-load.php(37): require_once('/home/ionicexce...')
#3 wp-admin/admin.php(34): require_once('/home/ionicexce...')
#4 wp-admin/theme-editor.php(10): require_once('/home/ionicexce...')
#5 {main}

**Comment by hsimah** [comment]
Are you calling the function in a hook callback? I use the `graphql_register_types` action like this:
```
    add_action('graphql_register_types', function () {
      register_graphql_facet_type('tutorial');
    });
```

**Comment by justlevine** [comment]
Closing as this is currently working and has [a WPUnit test]( https://github.com/hsimah-services/wp-graphql-facetwp/blob/develop/tests/wpunit/AccessFunctionsTest.php#L65)
