### ISSUE TITLE
Add support for sort facet

### ISSUE THREAD

**Issue by konstantinbrazhnik** [hsimah-services/wp-graphql-facetwp#24]
FacetWP has a sort facet that allows you to specify different ways to sort the returned data based on preset sort indexes. It would be great to have a sort GraphQL input type so that the data could be returned based on one of the preset sorts.

**Comment by konstantinbrazhnik** [comment]
@hsimah My intent is to build this functionality. I think FacetWP has evolved significantly since you created the initial version of this plugin. With WPEngine jumping into the GraphQL space so intensely, I think there might be a resurgence of interest in these tools and this plugin. We would be happy to contribute to building out full integration with more recent FacetWP features.

**Comment by hsimah** [comment]
@konstantinbrazhnik sorry for the delayed response - I missed the GitHub notifications. I would love to have some contributors on this. I moved away from working around Wordpress a long time ago and haven't found the time to really keep this up to date. If you are keen to help out I am happy to add you as a contributor to the repository and work with you on changes. I would love some sanity tests.
